# Generated by Django 4.2.1 on 2023-05-25 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('interest', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='student_pictures/')),
                ('resume', models.FileField(upload_to='student_resumes/')),
                ('certificates', models.FileField(upload_to='student_certificates/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
